server:
  port: 0

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

telegram:
  botToken: {TELEGRAM_BOT_TOKEN}

auth:
  password:
    encoder:
      strength: 12

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}
  accessExpirationMs: 3600000 # 1 час
  refreshExpirationMs: 604800000 # 7 дней

admin:
  secret:
    password: ${ADMIN_SECRET_PASSWORD}
moderator:
  secret:
    password: ${MANAGER_SECRET_PASSWORD}