spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Конфигурация JWT (нужен ТОЛЬКО секрет для ВАЛИДАЦИИ токенов)
# Секрет должен быть ТОЧНО ТАКИМ ЖЕ, как в auth-service!
jwt:
  secret: ${JWT_SECRET}